#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "User uid: $(id -u abc)"
echo "User gid: $(id -g abc)"

mkdir -p /config/.local/share/Terraria /world

[[ ! -f /config/.local/share/Terraria/favorites.json ]] && \
    cp /defaults/favorites.json /config/.local/share/Terraria/

if [[ ! -f /config/serverconfig.txt ]]; then
    cat > /config/serverconfig.txt <<EOF
world=/world/World.wld
worldpath=/world
worldname=Terraria
autocreate=2
maxplayers=8
port=7777
password=
motd=Welcome to Terraria!
EOF
fi


chown -R abc:abc /app/terraria /config /world
chmod 644 /config/serverconfig.txt